contacts/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required


from contacts.views import ContactsTableView

urlpatterns = [

    # Contacts URL
    url(r'^contacts/$', views.contacts, name='contacts'),
    # Detail page for a single contact
    url(r'^contact/(?P<contact_id>\d+)/$', views.contact, name='contact'),
    # Page for adding a new contact
    url(r'^new_contact/$', views.new_contact, name='new_contact'),

    # Page for adding a new comment
    url(r'^new_comment/(?P<contact_id>\d+)/$', views.new_comment, name='new_comment'),
    # Page for editing an comment
    url(r'^edit_comment/(?P<comment_id>\d+)/$', views.edit_comment, name='edit_comment'),
    # Page for deleting a comment
    url(r'^delete_comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

    # Delete Contact

    url(r'^delete_contact/(?P<contact_id>\d+)/$', views.delete_contact, name='delete_contact'),

    # Display all contacts in a table
    url(r'^contacts_table/$', login_required(ContactsTableView.as_view()), name='contacts_table'),

    # Editinng contact
    url(r'^edit_contact/(?P<record_id>\d+)/$', views.edit_contact, name='edit_contact'),
]

learning_log/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'', include('contacts.urls', namespace='contacts')),
]

users/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views
urlpatterns = [
    # Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #Logout page
    url(r'^logout/', views.logout_view, name='logout'),
    # Registration page
    url(r'^register/', views.register, name='register'),
]

contacts/models.py
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import User

import django_tables2 as tables

import django_filters

from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import InlineCheckboxes
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit


from django.http import HttpResponse

from multiselectfield import MultiSelectField
PRODUCT_CHOICES = (
    ('SportsBook Live', 'SportsBook Live'),
    ('SportsBook Prematch', 'SportsBook Prematch'),
    ('WhiteLabel', 'WhiteLabel'),
    ('LandBased', 'LandBased'),
    ('Other', 'Other'),
)

from django_tables2.utils import A


# Create your models here.


class Customer(models.Model):
    business_type = models.CharField(max_length=80, verbose_name='Type of the contact')
    person_name = models.CharField(max_length=80, verbose_name='Name and Surname')
    company_name = models.CharField(max_length=80, blank=True, unique=True, verbose_name='Company')
    website = models.URLField(blank=True, verbose_name='WWW')
    country = CountryField()
    email = models.EmailField(blank=True, null=True, verbose_name='E-mail')
    skype = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    product = MultiSelectField(choices=PRODUCT_CHOICES)
    created_on = models.DateTimeField(auto_now_add=True)
    notes = models.CharField(max_length=300, blank=True)
    exibition = models.CharField(max_length=50, blank=True, verbose_name='Met on...')
    contacted_on = models.DateField(blank=True, null=True, verbose_name='Last contact')
    action_date = models.DateField(blank=True, null=True)
    account_manager = models.ForeignKey(User)

    def __str__(self):
        return u'%s  %s' % (self.company_name, self.person_name)

    class Meta:
        verbose_name_plural = 'customers'
        ordering = ['company_name']
        permissions = (
            ("view_customer", "Can see individual contact"),
            ("view_all_customers", "Can view a table with all contacts"),
        )


class Comment(models.Model):
    comment = models.CharField(max_length=3000)
    posted_by = models.ForeignKey(User)
    customer = models.ForeignKey(Customer)
    createdOn = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments'
        ordering = ['createdOn']


class ContactsTable(tables.Table):
    person_name = tables.LinkColumn('contacts:contact', args=[A('pk')])

    #view = tables.TemplateColumn('<a href="/contact/{{record.id}}"><span class="glyphicon glyphicon-user"></span></a>')
    #edit = tables.TemplateColumn('<a href="/edit_contact/{{record.id}}"><span class="glyphicon glyphicon-pencil"></a>')

    class Meta:
        model = Customer
        # add class="paleblue" to <table> tag
        attrs = {'class': 'paleblue'}
        fields = (
            'id',
            'person_name',
            'business_type',
            'company_name',
            'email',
            'skype',
            'phone',
            'product',
            'notes',
            'exibition',
            'contacted_on',
            'action_date',
        )


class ContactsFilter(django_filters.FilterSet):
    business_type = django_filters.CharFilter(lookup_expr='icontains')
    company_name = django_filters.CharFilter(lookup_expr='icontains')
    person_name = django_filters.CharFilter(lookup_expr='icontains')
    product = django_filters.CharFilter(lookup_expr='icontains')
    exibition = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = Customer
        fields = ['business_type', 'company_name', 'person_name', 'product', 'exibition']


class ContactsFilterFormHelper(FormHelper):
    form_method = 'GET'
    form_class = 'form-inline'
    layout = Layout(
        'business_type',
        'company_name',
        'person_name',
        'product',
        'exibition',
        Submit('submit', 'Apply Filter', css_class='btn btn-warning btn-sm'),
    )

contacts/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget, Select, CheckboxSelectMultiple
from django_countries.widgets import CountrySelectWidget
from .models import Customer, Comment

YEAR_CHOICES = ('2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020')

PRODUCT_CHOICES = (
    ('SportsBook Live', 'SportsBook Live'),
    ('SportsBook Prematch', 'SportsBook Prematch'),
    ('WhiteLabel', 'WhiteLabel'),
    ('LandBased', 'LandBased'),
)

CONTACT_TYPES = (
    ('Prospect', 'Prospect'),
    ('Competitor', 'Competitor'),
    ('Existing Customer', 'Existing Customer'),
    ('Product Provider', 'Product Provider'),
    ('Other', 'Other'),
)


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = [
            'business_type',
            'person_name',
            'company_name',
            'website',
            'country',
            'email',
            'skype',
            'phone',
            'product',
            'notes',
            'exibition',
            'contacted_on',
            'action_date',
            'account_manager',
        ]
        labels = {
            'business_type': 'Type of business',
            'person_name': 'Full name',
            'company_name': 'Company legal name',
            'website': 'WWW',
            'email': 'Contact email',
            'skype': 'Skype',
            'phone': 'Mobile phone',
            'product': 'Products ordered',
            'notes': 'Comments',
            'exibition': 'Place of first meeting',
            'contacted_on': 'Date of the last contact',
            'action_date': 'Next date we should contact',
            'account_manager': 'Account manager',
        }
        widgets = {
            'notes': forms.Textarea(attrs={'cols': 80}),
            'contacted_on': SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"), years=YEAR_CHOICES),
            'action_date': SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"), years=YEAR_CHOICES),
            'product': CheckboxSelectMultiple(choices=PRODUCT_CHOICES),
            'business_type': Select(choices=CONTACT_TYPES),
            'country': CountrySelectWidget(),
        }
        initial = {
            'action_date': 'Specify when the next contact should be made',
        }
       # Custome validator

        def clean_business_type(self):
            business_type = self.cleaned_data['business_type']
            num_words = len(business_type.split())
            if num_words < 2:
                raise forms.ValidationError("Please write more information about the type of business!")
            return business_type


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment', ]
        labels = {'comments': 'Comments'}
        widgets = {'comment': forms.Textarea(attrs={'cols': 80})}
    # Custome validator

    def clean_comment(self):
        comment = self.cleaned_data['comment']
        num_words = len(comment.split())
        if num_words < 5:
            raise forms.ValidationError("Please write more information!")
        return comment

contacts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Customer, Comment
from .forms import CustomerForm
from .forms import CommentForm
# Create your views here.

# Counting objects
from django.db.models import Count

# Tables
from django_tables2 import RequestConfig
from django.views.generic import TemplateView
from django_tables2 import SingleTableView
from .models import ContactsTable, ContactsFilter, ContactsFilterFormHelper

# Pagination
from django.core.paginator import Paginator

# Permission
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator


@login_required
def contacts(request):
    contacts = Customer.objects.all()
    context = {'contacts': contacts}
    return render(request, 'contacts/contacts.html', context)


@login_required
@permission_required('contacts.view_customer')
def contact(request, contact_id):
    '''Show one topic'''
    contact = Customer.objects.get(id=contact_id)
    comments = contact.comment_set.order_by('-createdOn')
    context = {'contact': contact, 'comments': comments}
    return render(request, 'contacts/contact.html', context)


@login_required
@permission_required('contacts.add_customer')
def new_contact(request):
    """Add a new contact."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CustomerForm()
    else:
        # POST data submitted; process data.
        form = CustomerForm(request.POST)
        if form.is_valid():
            new_customer = form.save(commit=False)
            new_customer.save()
            # unction determines the URL from a named URL pattern
            return HttpResponseRedirect(reverse('contacts:contacts_table'))
    context = {'form': form}
    return render(request, 'contacts/new_contact.html', context)

# Edit or view the comment


#@login_required
@permission_required('contacts.change_customer')
def edit_contact(request, record_id):
    """Edit an existing comment."""
    contact = Customer.objects.get(id=record_id)
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = CustomerForm(instance=contact)
    else:
        # POST data submitted; process data.
        form = CustomerForm(instance=contact, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('contacts:contact',
                                                args=[contact.id]))
    context = {'contact': contact, 'form': form}
    return render(request, 'contacts/edit_contact.html', context)


@login_required
def new_comment(request, contact_id):
    """Add a new comment for a particular Contact."""
    contact = Customer.objects.get(id=contact_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CommentForm()
    else:
        # POST data submitted; process data.
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.posted_by = request.user
            new_entry.customer = contact
            new_entry.save()
            return HttpResponseRedirect(reverse('contacts:contact', args=[contact_id]))
    context = {'contact': contact, 'form': form}
    return render(request, 'contacts/new_comment.html', context)


@login_required
def edit_comment(request, comment_id):
    """Edit an existing comment."""
    comment = Comment.objects.get(id=comment_id)
    contact = comment.customer
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = CommentForm(instance=comment)
    else:
        # POST data submitted; process data.
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('contacts:contact',
                                                args=[contact.id]))
    context = {'comment': comment, 'contact': contact, 'form': form}
    return render(request, 'contacts/edit_comment.html', context)


@login_required
def delete_comment(request, comment_id):
   # delete an object and send a confirmation response
    item = Comment.objects.get(id=comment_id)
    contact = item.customer
    item.delete()
    return HttpResponseRedirect(reverse('contacts:contact', args=[contact.id]))


#@login_required
@permission_required('contacts.delete_customer')
def delete_contact(request, contact_id):
   # delete an object and send a confirmation response
    item = Customer.objects.get(id=contact_id)
    item.delete()
    return HttpResponseRedirect(reverse('contacts:contacts_table'))


class PagedFilteredTableView(SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'

    def get_queryset(self, **kwargs):
        qs = super(PagedFilteredTableView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super(PagedFilteredTableView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        return context


@method_decorator(permission_required('contacts.view_all_customers'), name='dispatch')
class ContactsTableView(PagedFilteredTableView):
    model = Customer
    table_class = ContactsTable
    template_name = 'contacts/contacts_table.html'
    paginate_by = 8
    filter_class = ContactsFilter
    formhelper_class = ContactsFilterFormHelper

contacts/templates/contacts/contact.html
{% extends 'learning_logs/base.html' %}
{# Load the tag library #}
{% load bootstrap3 %}


{% block header %}


<h3>{{contact}}</h3>
<p>You can edit this contact:
        <a href="{% url 'contacts:edit_contact' contact.id %}" class="btn btn-success btn-sm">
          <span class="glyphicon glyphicon-pencil"></span> Edit
        </a>
        You can delete this contact:
        <a href="{% url 'contacts:delete_contact' contact.id%}" class="btn btn-danger btn-sm delete" data-confirm="You are going to delete a Type of Sport! Continue?">
          <span class="glyphicon glyphicon-pencil"></span> Delete
        </a>
      </p>
<table class="table table-striped">
    <tbody>

    <tr>
             <th>This contact is:</th>
             <td>{{contact.business_type}}</td>
    </tr>
    <tr>
             <th>The full name of the contact person is:</th>
             <td>{{contact.person_name}}</td>
    </tr>
    <tr>
            <th>The legal name of the company is:</th>
             <td>{{contact.company_name}}</td>
    </tr>
    <tr>
            <th>The official website is:</th>
             <td>{{contact.website}}</td>
    </tr>
    <tr>
            <th>Contact email is:</th>
             <td>{{contact.email}}</td>
    </tr>
    <tr>
            <th>The skype is:</th>
             <td>{{contact.skype}}</td>
    </tr>
    <tr>
            <th>Contact mobile phone is:</th>
             <td>{{contact.phone}}</td>
    </tr>
    <tr>
            <th>The company is interested in:</th>
             <td>{{contact.product}}</td>
    </tr>
    <tr>
            <th>Notes:</th>
             <td>{{contact.notes}}</td>
    </tr>
    <tr>
            <th>The contact was met at:</th>
             <td>{{contact.exibition}}</td>
    </tr>
    <tr>
            <th>Date of contact:</th>
             <td>{{contact.contacted_on}}</td>
    </tr>
    <tr>
            <th>The contact should be contacted at: </th>
             <td>{{contact.action_date}}</td>
    </tr>
    <tr>
            <th>Account manager is:</th>
             <td>{{contact.account_manager}}</td>
    </tr>

    </tbody>
</table>

{% endblock header %}


{% block content %}
  <p>
    {% buttons %}
    <a href="{% url 'contacts:new_comment' contact.id %}" class="btn btn-primary" role = 'button'>{% bootstrap_icon "pushpin" %} add comment for this contact</a>
    {% endbuttons %}
  </p>
  {% for comment in comments %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Added: {{ comment.createdOn|date:'M d, Y H:i' }}</h4>
      {% buttons %}
            <a href="{% url 'contacts:edit_comment' comment.id %}" class="btn btn-success" role = 'button'>{% bootstrap_icon "pencil" %} edit comment </a>
            <a href="{% url 'contacts:delete_comment' comment.id %}" class="btn btn-danger delete" role = 'button' data-confirm="Are you sure to delete this comment?" >{% bootstrap_icon "remove" %} delete comment </a>
      {% endbuttons %}

    </div>
      <div class="panel-body">
          {{ comment.comment|linebreaks }}
      </div>
    </div> <!-- panel -->

    {% empty %}
    There are no more comments for this Contact yet.



  {% endfor %}



<script type="text/javascript">
  var deleteLinks = document.querySelectorAll('.delete');

for (var i = 0; i < deleteLinks.length; i++) {
  deleteLinks[i].addEventListener('click', function(event) {
      event.preventDefault();

      var choice = confirm(this.getAttribute('data-confirm'));

      if (choice) {
        window.location.href = this.getAttribute('href');
      }
  });
}
</script>

{% endblock content %}

contacts/templates/contacts/contacts.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h3>List of all Contacts</h3>
{% endblock header %}

{% block content %}


<table class="table-condensed">
  <tbody>
    {% for contact in contacts %}
       <tr>
         <td>
               <a href="{% url 'contacts:contact' contact.id %}">{{ contact }}</a>
         </td>

                 <td>
                        <a style="color: red" href="{% url 'contacts:delete_contact' contact.id%}" class="red delete" data-confirm="You are going to delete a Type of Sport! Continue?">{% bootstrap_icon "remove" %} </a>
                 </td>



       </tr>
       {% empty %}
                <li>No contacts have been added yet.</li>
    {% endfor %}
  </tbody>
</table>

        {% buttons %}
         <h3><a href="{% url 'contacts:new_contact' %}"class="btn btn-primary" role = 'button'>{% bootstrap_icon "pushpin" %} New Contact</a></h3>
        {% endbuttons %}


<script type="text/javascript">
  var deleteLinks = document.querySelectorAll('.delete');

for (var i = 0; i < deleteLinks.length; i++) {
  deleteLinks[i].addEventListener('click', function(event) {
      event.preventDefault();

      var choice = confirm(this.getAttribute('data-confirm'));

      if (choice) {
        window.location.href = this.getAttribute('href');
      }
  });
}
</script>

{% endblock content %}

contacts/templates/contacts/contacts_table.html
{% extends "learning_logs/base.html" %}
{% load render_table from django_tables2 %}
{% load django_tables2 crispy_forms_tags %}


{% load bootstrap3 %}

{% load static %}

{% block header %}
<h3>Table of available contacts</h3>
        {% buttons %}
         <h3><a href="{% url 'contacts:new_contact' %}"class="btn btn-primary" role = 'button'>{% bootstrap_icon "pushpin" %} New Contact</a></h3>
        {% endbuttons %}
{% endblock header %}


{% block content %}
{% crispy filter.form filter.form.helper %}
</br>
{% render_table table %}


{% endblock content %}

contacts/templates/contacts/edit_comment.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <p><a href="{% url 'contacts:contact' contact.id %}">{{ contact }}</a></p>
  <p>Edit comment:</p>
  <form action="{% url 'contacts:edit_comment' comment.id %}" method='post'>
   {% csrf_token %}
   {% bootstrap_form form %}
   {% buttons %}
   <button name="submit" class="btn btn-primary">save changes</button>
   {% endbuttons %}
  </form>
{% endblock content %}

contacts/templates/contacts/edit_contact.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h3><a href="{% url 'contacts:contact' contact.id %}">{{ contact }}</a></h3>
  <p>View or Edit Contact:</p>
  <form action="{% url 'contacts:edit_contact' contact.id %}" method='post'>
   {% csrf_token %}
   {% bootstrap_form form %}
   {% buttons %}
   <button name="submit" class="btn btn-primary">save changes</button>
   {% endbuttons %}
  </form>
{% endblock content %}

contacts/templates/contacts/new_comment.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <p><a href="{% url 'contacts:contact' contact.id %}">{{ contact }}</a></p>
  <p>Add a new comment to the contact: {{ contact }}</p>
  <form action="{% url 'contacts:new_comment' contact.id %}" method='post' class="form">
       {% csrf_token %}
       {% bootstrap_form form %}
        {% buttons %}
       <button name='submit' class="btn btn-primary">{% bootstrap_icon "pushpin" %} add comment</button>
       {% endbuttons %}
     </form>
{% endblock content %}

contacts/templates/contacts/new_contact.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>Add the details of the new customer / contact:</h3>
{% endblock header %}

{% block content %}
<form action="{% url 'contacts:new_contact' %}" method='post' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit" class="btn btn-primary">{% bootstrap_icon "pushpin" %} add Details</button>
  {% endbuttons %}
 </form>
{% endblock content %}