contacts/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required


from contacts.views import ContactsTableView

urlpatterns = [

    # Contacts URL
    url(r'^contacts/$', views.contacts, name='contacts'),
    # Detail page for a single contact
    url(r'^contact/(?P<contact_id>\d+)/$', views.contact, name='contact'),
    # Page for adding a new contact
    url(r'^new_contact/$', views.new_contact, name='new_contact'),

    # Page for adding a new comment
    url(r'^new_comment/(?P<contact_id>\d+)/$', views.new_comment, name='new_comment'),
    # Page for editing an comment
    url(r'^edit_comment/(?P<comment_id>\d+)/$', views.edit_comment, name='edit_comment'),
    # Page for deleting a comment
    url(r'^delete_comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

    # Delete Contact

    url(r'^delete_contact/(?P<contact_id>\d+)/$', views.delete_contact, name='delete_contact'),

    # Display all contacts in a table
    url(r'^contacts_table/$', login_required(ContactsTableView.as_view()), name='contacts_table'),

    # Editinng contact
    url(r'^edit_contact/(?P<record_id>\d+)/$', views.edit_contact, name='edit_contact'),
]

learning_log/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'', include('contacts.urls', namespace='contacts')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

from learning_logs.views import TopicsTableView

urlpatterns = [
    # Home view
    url(r'^$', views.index, name='index'),
    # Tipics URL
    url(r'^topics/$', views.topics, name='topics'),
    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # Page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    # Page for deleting an entry
    url(r'^delete_entry/(?P<delete_id>\d+)/$', views.delete_entry, name='delete_entry'),
    # Delete Topic
    url(r'^delete_topic/(?P<delete_id>\d+)/$', views.delete_topic, name='delete_topic'),
    # Display all topics in a table
    url(r'^topics_table/$', login_required(TopicsTableView.as_view()), name='topics_table'),
    # Editinng topic
    url(r'^edit_topic/(?P<record_id>\d+)/$', views.edit_topic, name='edit_topic'),

]

users/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views
urlpatterns = [
    # Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #Logout page
    url(r'^logout/', views.logout_view, name='logout'),
    # Registration page
    url(r'^register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField

import django_tables2 as tables
import django_filters
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import InlineCheckboxes
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field, Div

from django_tables2.utils import A
from django_countries.widgets import CountrySelectWidget


# A topic a user is learning about

# Managers / Manager methods


class TopicManager (models.Manager):
    def event_finder(self, keyword):
        # Self refers to the manager itself
        return self.filter(event__icontains=keyword)

# Modifying Initial Manager QuerySets


class MaleManager(models.Manager):
    def get_queryset(self):
        return super(MaleManager, self).get_queryset().filter(gender='M')


class FemaleManager(models.Manager):
    def get_queryset(self):
        return super(FemaleManager, self).get_queryset().filter(gender='F')


class Topic(models.Model):
    sport = models.CharField(max_length=200, default='')
    event = models.CharField(max_length=200)
    asoc = models.CharField(max_length=200, blank=True)
    league = models.CharField(max_length=200, blank=True)
    devision = models.CharField(max_length=200, blank=True,)
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')), blank=True)
    country = CountryField(blank=True, null=True)
    region = models.CharField(max_length=200, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    managers = TopicManager()
    objects = models.Manager()
    man = MaleManager()
    female = FemaleManager()

    class Meta:
        permissions = (
            ("view_sport", "Can see individual sport record"),
            ("view_all_sports", "Can view a table with all sports"),
        )
        ordering = ['sport']

    def __str__(self):
        return u'Sport is %s | Event is %s | Association is  %s | League is %s | Devision is %s | Gender is %s | Country is %s | Region is %s' % (self.sport, self.event, self.asoc, self.league, self.devision, self.gender, self.country, self.region)


class Entry(models.Model):
    '''Something specific about topic'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.URLField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

        def __str__(self):
            """Return a string representation of the model."""
            return self.text

# Table


class TopicTable(tables.Table):
    sport = tables.LinkColumn('learning_logs:topic', args=[A('pk')])

    class Meta:
        model = Topic
        # add class="paleblue" to <table> tag
        attrs = {'class': 'paleblue ', 'id': 'my_table'}
        fields = (
            'id',
            'sport',
            'country',
            'event',
            'asoc',
            'league',
            'devision',
            'gender',
            'region',
        )


# Filters
class TopicFilter(django_filters.FilterSet):
    sport = django_filters.CharFilter(lookup_expr='icontains')
    event = django_filters.CharFilter(lookup_expr='icontains')
    asoc = django_filters.CharFilter(lookup_expr='icontains')
    league = django_filters.CharFilter(lookup_expr='icontains')
    devision = django_filters.CharFilter(lookup_expr='icontains')
    # country = django_filters.CharFilter(lookup_expr='icontains')
    region = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = Topic
        fields = ['sport', 'event', 'asoc', 'league', 'devision', 'gender', 'country']


class TopicFilterFormHelper(FormHelper):
    form_method = 'GET'
    form_class = 'form-inline'
    layout = Layout(
        Div(
            Div('sport', css_class='col-sm-3'),
            Div('event', css_class='col-sm-3'),
            Div('asoc', css_class='col-sm-3'),
            Div('league', css_class='col-sm-3'),
            css_class='row'),
        Div(
            Div('gender', css_class='col-sm-3'),
            Div('devision', css_class='col-sm-3'),
            Div('country', css_class='col-sm-6'),
            css_class='row'),

        Div(Div(Submit('submit', 'Apply Filter', css_class='btn btn-warning btn-sm'), css_class='col-sm-3 pull-left', style='margin-top: 10px;'), css_class='row')
    )

learning_logs/forms.py
from django import forms
from .models import Topic, Entry
from django.forms.widgets import SelectDateWidget, Select, CheckboxSelectMultiple
from django_countries.widgets import CountrySelectWidget

GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'sport',
            'event',
            'asoc',
            'league',
            'devision',
            'gender',
            'country',
            'region',
        ]

        labels = {
            'sport': 'Sport:',
            'event': 'Event:',
            'asoc': 'Association:',
            'league': 'League:',
            'devision': 'Division',
            'gender': 'Gender',
            'country': 'Country',
            'region': 'Region',
        }
        widgets = {'country': CountrySelectWidget()}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'URL:'}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm
from .forms import EntryForm
# Create your views here.

# Counting objects
from django.db.models import Count

# Tables
from django_tables2 import RequestConfig
from django.views.generic import TemplateView
from django_tables2 import SingleTableView
from .models import TopicTable, TopicFilter, TopicFilterFormHelper

# Permission
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator


def index(request):
    '''Home page for learning_log'''
    logged = request.user
    context = {'logged': logged}
    return render(request, 'learning_logs/index.html', context)


@login_required
def topics(request):
    topics = Topic.objects.annotate(n_ent=Count('entry'))
    total_entries = Entry.objects.count()
    context = {'topics': topics, 'total_entries': total_entries}
    return render(request, 'learning_logs/topics.html', context)


@login_required
@permission_required('learning_logs.view_sport')
def topic(request, topic_id):
    '''Show one topic'''
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    # if topic.owner != request.user:
    #raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
@permission_required('learning_logs.add_topic')
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # unction determines the URL from a named URL pattern
            return HttpResponseRedirect(reverse('learning_logs:topics_table'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


#@login_required
@permission_required('learning_logs.change_topic')
def edit_topic(request, record_id):
    """Edit an existing topic."""
    topic = Topic.objects.get(id=record_id)
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = TopicForm(instance=topic)
    else:
        # POST data submitted; process data.
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@permission_required('learning_logs.change_entry')
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # check for user
    # if topic.owner != request.user:
    #raise Http404
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@permission_required('learning_logs.delete_entry')
def delete_entry(request, delete_id):
   # delete an object and send a confirmation response
    item = Entry.objects.get(id=delete_id)
    topic = item.topic
    item.delete()
    return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))


@permission_required('learning_logs.delete_topic')
def delete_topic(request, delete_id):
   # delete an object and send a confirmation response
    item = Topic.objects.get(id=delete_id)
    item.delete()

    return HttpResponseRedirect(reverse('learning_logs:topics_table'))

# Tables--------------------------------------------------------------------------


class PagedFilteredTableView(SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'

    def get_queryset(self, **kwargs):
        qs = super(PagedFilteredTableView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super(PagedFilteredTableView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        return context


@method_decorator(permission_required('learning_logs.view_all_sports'), name='dispatch')
class TopicsTableView(PagedFilteredTableView):
    model = Topic
    table_class = TopicTable
    template_name = 'learning_logs/topics_table.html'
    paginate_by = 40
    filter_class = TopicFilter
    formhelper_class = TopicFilterFormHelper

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
       <meta charset="utf-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.2.0/jquery-confirm.min.css">
       <title>BetInvest B2B Portal</title>
       {% bootstrap_css %}
       {% bootstrap_javascript %}
       {% load static %}

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

     <link rel="stylesheet" href="/static/css/main.css">


     <link href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" rel="stylesheet">
     <script src="/static/js/main.js"></script>

</head>

<body>
       <!-- Static navbar -->
       <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
              BetInvest B2B Portal</a>
</div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics_table' %}">SportsData</a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'contacts:contacts_table' %}">Contacts</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
                   {% if user.username == 'll_admin' %}
              <li><a href="{% url 'users:register' %}">register</a></li>
                   {% endif %}
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


<div class="container">
            <div class="page-header">
                    {% block header %}{% endblock header %}
            </div>
            <div>
                    {% block content %}{% endblock content %}
            </div>
 </div> <!-- /container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
   {% csrf_token %}
   {% bootstrap_form form %}
   {% buttons %}
   <button name="submit" class="btn btn-primary">save changes</button>
   {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
  <p>View or Edit Record:</p>
  <form action="{% url 'learning_logs:edit_topic' topic.id %}" method='post'>
   {% csrf_token %}
   {% bootstrap_form form %}
   {% buttons %}
   <button name="submit" class="btn btn-primary">save changes</button>
   {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
       <h1> </h1>
    </div>
{% endblock header %}

{% block content %}
<div class="well">
{% if user.is_authenticated %}
    <h3>Hello, {{ user.username }}.</h3>

{% else %}
    <h2><a href="{% url 'users:login' %}">Log in</a> to use the system.</h2>
    <p>Or ask a head of B2B department for your login details.</p>
{% endif %}
</div>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
       {% csrf_token %}
       {% bootstrap_form form %}
        {% buttons %}
       <button name='submit' class="btn btn-primary">{% bootstrap_icon "pushpin" %} add entry</button>
       {% endbuttons %}
     </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>Add a new Sport:</h3>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit" class="btn btn-primary">{% bootstrap_icon "pushpin" %} add Sport</button>
  {% endbuttons %}
 </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{# Load the tag library #}
{% load bootstrap3 %}


{% block header %}

<div class="well">
<p>You can edit this record:
        <a href="{% url 'learning_logs:edit_topic' topic.id %}" class="btn btn-success btn-sm">
          <span class="glyphicon glyphicon-pencil"></span> Edit
        </a>
        You can delete this record:
        <a href="{% url 'learning_logs:delete_topic' topic.id%}" class="btn btn-danger btn-sm delete" data-confirm="You are going to delete a RECORD! Continue?">
          <span class="glyphicon glyphicon-remove"></span> Delete
        </a>
    </p>
</div>
<table class="table table-striped">
    <tbody>
    <thead>
            <tr>
              <th>Sport: (Спотр)</th>
              <th>Type: (Тип)</th>
              <th>Association: (Ассоциация)</th>
              <th>League: (Лига)</th>
              <th>Devision: (Девизион)</th>
              <th>Gender: (Пол)</th>
              <th>Country: (Страна)</th>
              <th>Region if any: (Регион)</th>
            </tr>
          </thead>

    <tr>

             <td>{{topic.sport}}</td>

             <td>{{topic.event}}</td>

             <td>{{topic.asoc}}</td>

             <td>{{topic.league}}</td>

             <td>{{topic.devision}}</td>

             <td>{{topic.gender}}</td>

             <td>{{topic.country}}</td>

             <td>{{topic.region}}</td>
    </tr>



    </tbody>
</table>

{% endblock header %}



{% block content %}
  <p>
    {% buttons %}
    <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-primary" role = 'button'>{% bootstrap_icon "pushpin" %} add new WWW for this record</a>
    {% endbuttons %}
  </p>



    <!--Table-->
    <table class="table table-striped">
    <tbody>
            <thead>
            <tr>
              <th>Url Link</th>
              <th>Click</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
          </thead>
  {% for entry in entries %}
         <tr>
             <td>{{entry.text}}</td>

             <td><a href="{{entry.text}}" target="_blank">VISIT</a></td>

             <td><a href="{% url 'learning_logs:edit_entry' entry.id %}" class="btn btn-success btn-sm" role = 'button'>{% bootstrap_icon "pencil" %} edit URL </a></td>

             <td><a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-danger btn-sm delete" role = 'button' data-confirm="Are you sure to delete this URL?" >{% bootstrap_icon "remove" %} delete URL </a></td>
         </tr>
  {% empty %}
      There are no more URLs for this Record yet.
  {% endfor %}
    </tbody>
    </table>
<a href="{% url 'learning_logs:topics_table'%}" class="btn btn-warning btn-sm" role = 'button'>{% bootstrap_icon "list" %} Back to all Sports</a>


<script type="text/javascript">
  var deleteLinks = document.querySelectorAll('.delete');

for (var i = 0; i < deleteLinks.length; i++) {
  deleteLinks[i].addEventListener('click', function(event) {
      event.preventDefault();

      var choice = confirm(this.getAttribute('data-confirm'));

      if (choice) {
        window.location.href = this.getAttribute('href');
      }
  });
}
</script>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h3>List of all Sports</h3>
{% endblock header %}

{% block content %}

<h4>There are {{ total_entries }} entries added.</h4>
<table class="table-condensed">
  <tbody>
    {% for topic in topics %}
       <tr>
         <td>
               <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                {% if topic.n_ent > 0 %}
                    <small><span class="label label-danger">{{ topic.n_ent}}</span></small>
                {% endif %}
          </td>

                 <td>
                        <small><a href="{% url 'learning_logs:delete_topic' topic.id%}" class="red delete" data-confirm="You are going to delete a Type of Sport! Continue?">{% bootstrap_icon "remove" %} </a></small>
                 </td>

       </tr>
       {% empty %}
                <li>No topics have been added yet.</li>
    {% endfor %}
  </tbody>
</table>

        {% buttons %}
        <h3><a href="{% url 'learning_logs:new_topic' %}"class="btn btn-primary" role = 'button'>{% bootstrap_icon "pushpin" %} New Sport</a></h3>
        {% endbuttons %}


<script type="text/javascript">
  var deleteLinks = document.querySelectorAll('.delete');

for (var i = 0; i < deleteLinks.length; i++) {
  deleteLinks[i].addEventListener('click', function(event) {
      event.preventDefault();

      var choice = confirm(this.getAttribute('data-confirm'));

      if (choice) {
        window.location.href = this.getAttribute('href');
      }
  });
}
</script>

{% endblock content %}

learning_logs/templates/learning_logs/topics_table.html
{% extends "learning_logs/base.html" %}
{% load render_table from django_tables2 %}
{% load django_tables2 crispy_forms_tags %}


{% load bootstrap3 %}

{% load static %}

{% block header %}
<h3>Table of available events</h3>
        {% buttons %}
         <h3><a href="{% url 'learning_logs:new_topic' %}"class="btn btn-primary" role = 'button'>{% bootstrap_icon "pushpin" %} New Event</a></h3>
        {% endbuttons %}
{% endblock header %}


{% block content %}
{% crispy filter.form filter.form.helper %}
</br>
{% render_table table %}


{% endblock content %}